import type { Metadata } from "next";
import localFont from "next/font/local";
import Particles from "./components/particles/particles";
import "./globals.css";

const zhcn = localFont({
  src: "./fonts/zh-cn.ttf",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Genshin Algolia Search",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <Particles />
      </head>
      <body
        className={`${zhcn.className} bg-background-primary text-gray-200 relative`}>
        <div id="mybody"></div>
        <div className="absolute w-full">{children}</div>
      </body>
    </html>
  );
}
